/* Not autogenerated. */

#ifdef _WIN32
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#pragma once

#ifndef __ICoreWindowInterop_FWD_DEFINED__
#define __ICoreWindowInterop_FWD_DEFINED__
typedef interface ICoreWindowInterop ICoreWindowInterop;
#ifdef __cplusplus
interface ICoreWindowInterop;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>
#include <ocidl.h>
#include <dxgi.h>
#include <d3dcommon.h>

#ifdef __cplusplus
extern "C" {
#endif

DEFINE_GUID(IID_ICoreWindowInterop, 0x45d64a29, 0xa63e, 0x4cb6, 0xb4,0x98, 0x57,0x81,0xd2,0x98,0xcb,0x4f);

#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("45d64a29-a63e-4cb6-b498-5781d298cb4f")
ICoreWindowInterop : public IUnknown {
  virtual HRESULT STDMETHODCALLTYPE get_WindowHandle(HWND *hwnd) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_MessageHandled(boolean value) = 0;
};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ICoreWindowInterop, 0x45d64a29, 0xa63e, 0x4cb6, 0xb4,0x98, 0x57,0x81,0xd2,0x98,0xcb,0x4f)
#endif
#else
typedef struct ICoreWindowInteropVtbl
{
BEGIN_INTERFACE
  
  /*** IUnknown methods ***/
  HRESULT (STDMETHODCALLTYPE *QueryInterface)(
    ICoreWindowInterop *This,
    REFIID riid,
    void **ppvObject
  );
  ULONG (STDMETHODCALLTYPE *AddRef)(ICoreWindowInterop *This);
  ULONG (STDMETHODCALLTYPE *Release)(ICoreWindowInterop *This);

  /*** ICoreWindowInterop methods ***/

  HRESULT (STDMETHODCALLTYPE *get_WindowHandle)(ICoreWindowInterop *This, HWND *hwnd);
  HRESULT (STDMETHODCALLTYPE *put_MessageHandled)(ICoreWindowInterop *This, boolean value);
END_INTERFACE
} ICoreWindowInteropVtbl;

interface ICoreWindowInterop
{
    CONST_VTBL struct ICoreWindowInteropVtbl *lpVtbl;
};

#define ICoreWindowInterop_AddRef(This) ((This)->lpVtbl->AddRef(This))
#define ICoreWindowInterop_Release(This) ((This)->lpVtbl->Release(This))
#define ICoreWindowInterop_get_WindowHandle(This, hwnd) ((This)->lpVtbl->get_WindowHandle(This, hwnd))
#define ICoreWindowInterop_put_MessageHandled(This, value) ((This)->lpVtbl->put_MessageHandled(This, value))

#endif // __cplusplus

#ifdef __cplusplus
}
#endif
